name: CD Pipeline

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: sudo docker pull ratankotipalli/sentiment_analysis_model-fastapi:latest
      - name: Delete Old Docker Container
        run: sudo docker rm -f sentiment_analysis_model-fastapi-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8001 --name sentiment_analysis_model-fastapi-container ratankotipalli/sentiment_analysis_model-fastapi
